# Generated by Django 4.2.13 on 2024-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_evaluacion_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=80, null=True, verbose_name='Observaciones'),
        ),
    ]
